import { Component } from "react";


// add more institution including polytechnics
const institutions:{ [key: string]: string } =  {
    "Abia State University": "Institution",
    "Abubakar Tafawa Balewa University": "Institution",
    "Achievers University": "Institution",
    "Adamawa State University Mubi": "Institution",
    "Adekunle Ajasin University": "Institution",
    "Adeleke University": "Institution",
    "Afe Babalola University": "Institution",
    "African University of Science & Technology": "Institution",
    "Ahmadu Bello University": "Institution",
    "Ajayi Crowther University": "Institution",
    "Akwa Ibom State University of Technology": "Institution",
    "Al-Hikmah University": "Institution",
    "Al-Qalam University": "Institution",
    "Ambrose Alli University": "Institution",
    "American University of Nigeria": "Institution",
    "Anambra State University of Science & Technology": "Institution",
    "Babcock University": "Institution",
    "Bauchi State University": "Institution",
    "Bayero University": "Institution",
    "Baze University": "Institution",
    "Bells University of Technology": "Institution",
    "Benson Idahosa University": "Institution",
    "Benue State University": "Institution",
    "Bingham University": "Institution",
    "Bowen University": "Institution",
    "Bukar Abba Ibrahim University": "Institution",
    "Caleb University": "Institution",
    "Caritas University": "Institution",
    "CETEP City University": "Institution",
    "Covenant University Ota": "Institution",
    "Crawford University Igbesa": "Institution",
    "Crescent University": "Institution",
    "Cross River State University of Science &Technology": "Institution",
    "Delta State University Abraka": "Institution",
    "Ebonyi State University": "Institution",
    "Ekiti State University": "Institution",
    "Elizade University": "Institution",
    "Enugu State University of Science and Technology": "Institution",
    "Evangel University": "Institution",
    "Federal University Gashua": "Institution",
    "Federal University of Petroleum Resources": "Institution",
    "Federal University of Technology": "Institution",
    "Federal University": "Institution",
    "Fountain Unveristy": "Institution",
    "Godfrey Okoye University": "Institution",
    "Gombe State Univeristy": "Institution",
    "Gregory University": "Institution",
    "Ibrahim Badamasi Babangida University": "Institution",
    "Igbinedion University Okada": "Institution",
    "Ignatius Ajuru University of Education": "Institution",
    "Imo State University": "Institution",
    "Jigawa State University": "Institution",
    "Joseph Ayo Babalola University": "Institution",
    "Kaduna State University": "Institution",
    "Kano University of Science & Technology": "Institution",
    "Kebbi State University": "Institution",
    "Kogi State University Anyigba": "Institution",
    "Kwara State University": "Institution",
    "Kwararafa University": "Institution",
    "Ladoke Akintola University of Technology": "Institution",
    "Lagos State University Ojo": "Institution",
    "Landmark University": "Institution",
    "Lead City University": "Institution",
    "Madonna University": "Institution",
    "Mcpherson University": "Institution",
    "Michael Okpara Uni. of Agric.": "Institution",
    "Modibbo Adama University of Technology": "Institution",
    "Nasarawa State University": "Institution",
    "National Open University of Nigeria": "Institution",
    "Niger Delta Unversity": "Institution",
    "Nigeria Police Academy Wudil": "Institution",
    "Nigerian Defence Academy": "Institution",
    "Nigerian-Turkish Nile University": "Institution",
    "Nnamdi Azikiwe University": "Institution",
    "Northwest University": "Institution",
    "Novena University": "Institution",
    "Obafemi Awolowo University": "Institution",
    "Obong University": "Institution",
    "Oduduwa University": "Institution",
    "Olabisi Onabanjo University Ago-Iwoye": "Institution",
    "Ondo State University of Science & Technology": "Institution",
    "Osun State University": "Institution",
    "Pan-African University": "Institution",
    "Paul University": "Institution",
    "Plateau State University": "Institution",
    "Redeemer's University": "Institution",
    "Renaissance University": "Institution",
    "Rhema University": "Institution",
    "Rivers State University of Science & Technology": "Institution",
    "Salem University": "Institution",
    "Samuel Adegboyega University": "Institution",
    "Sokoto State University": "Institution",
    "Southwestern University": "Institution",
    "Tai Solarin Univ. of Education": "Institution",
    "Tansian University": "Institution",
    "Taraba State University": "Institution",
    "Technical University": "Institution",
    "Umaru Musa Yar'Adua University": "Institution",
    "University of Abuja": "Institution",
    "University of Agriculture": "Institution",
    "University of Benin": "Institution",
    "University of Calabar": "Institution",
    "University of Ibadan": "Institution",
    "University of Ilorin": "Institution",
    "University of Jos": "Institution",
    "University of Lagos": "Institution",
    "University of Maiduguri": "Institution",
    "University of Mkar": "Institution",
    "University of Nigeria": "Institution",
    "University of Port-Harcourt": "Institution",
    "University of Uyo": "Institution",
    "Usumanu Danfodiyo University": "Institution",
    "Veritas University": "Institution",
    "Wellspring University": "Institution",
    "Wesley Univ. of Science & Tech.": "Institution",
    "Western Delta University": "Institution"
  }
  
  
export class institutionList extends Component{

    /* Return lists of institution */
    static list(){
        const listOfinstitution:[] = []

        Object.entries(institutions).forEach(([key, value]) => {
            
            const institutionName = key
            const code = value
            const institutionObj = {key: institutionName, value: institutionName}
            listOfinstitution.push(institutionObj)
        });

        return listOfinstitution;
    }

}
